### ISSUE TITLE
An unhandled error occurred inside electron-rebuild

### ISSUE THREAD

**Issue by VisWong** [colinbdclark/osc.js#116]
Unable to find electron-prebuilt's version number, either install it or specify an explicit version

Error: Unable to find electron-prebuilt's version number, either install it or specify an explicit version
    at Object.<anonymous> (d:\vis\osc.js\node_modules\electron-rebuild\lib\src\cli.js:80:19)
    at Generator.next (<anonymous>)
    at d:\vis\osc.js\node_modules\electron-rebuild\lib\src\cli.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (d:\vis\osc.js\node_modules\electron-rebuild\lib\src\cli.js:4:12)
    at d:\vis\osc.js\node_modules\electron-rebuild\lib\src\cli.js:69:8
    at Object.<anonymous> (d:\vis\osc.js\node_modules\electron-rebuild\lib\src\cli.js:145:4)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)

Here is the console output after I following the instruction provided by the node-serialport project.

I did the below steps:
npm install --save-dev electron-rebuild
Add electron-rebuild to your project's package.json's install hook
Run npm install

Any one has ideas of the issue?

**Comment by colinbdclark** [comment]
Hi @VisWong, sorry to hear about the problem. Which version of osc.js are you using? If it's <code>2.2.0</code>, can you try the <code>2.2.1-dev.20180205T232925Z.6deb74c</code> dev release and let me know if that fixes your problem? I'm hoping to cut the final <code>2.2.1</code> release this week.

Also, which version of Electron are you using?

**Comment by VisWong** [comment]
My electron version is 1.8.4. I already try dev release and it is not working. I am node js newbie. Maybe there was something wrong when I doing the installation. In readme file, should I add "osc" at the bower and package file. Actually I tried with "osc" and without it. Both are leading the same error. Any possible stuff I did wrong? Thank you very much!

**Comment by colinbdclark** [comment]
Hi @VisWong, sorry for the delay in responding. I just cut the <code>2.2.1</code> release. Can you try it? You shouldn't need to user Bower, just npm. Your <code>package.json</code> file should look something like this:

    "dependencies": {
        "electron": "1.8.4",
        "osc": "2.2.1"
    }

I've updated the instructions for the latest version of Electron that I tested with. Personally, I don't use electron-rebuild when I build Electron applications (though it's a perfectly good tool). An .npmrc file should provide the information npm needs to build dependencies for the version of Electron you're using:

    target=1.8.4
    disturl=https://atom.io/download/electron
    runtime=electron
    build_from_source=true

If these don't work for you, I think I'll need to see more context for your application and how you're using osc.js before I can be of much help. You can also take a look at the [Electron example in the osc.js-examples repository](https://github.com/colinbdclark/osc.js-examples).

I hope this helps!

**Comment by colinbdclark** [comment]
Closing due to inactivity. I've tested with recent versions of Electron and osc.js seems to be working. Feel free to reopen this if you encounter further issues.
