### ISSUE TITLE
Option to use UDP without requiring osc-node-serialport.js

### ISSUE THREAD

**Issue by ThomasVROwl** [colinbdclark/osc.js#152]
The following error is thrown when running a build with node:
`...\build\webpack:\node_modules\bindings\bindings.js:178
  if (fileName.indexOf(fileSchema) === 0) {
^
TypeError: Cannot read property 'indexOf' of undefined
    at Function.t.getFileName (...\build\webpack:\node_modules\bindings\bindings.js:178:1)
    at t (...\build\webpack:\node_modules\bindings\bindings.js:82:1)
    at Object.<anonymous> (...\build\webpack:\node_modules\@serialport\bindings\lib\win32.js:1:1)
    at n (...\build\webpack:\webpack\bootstrap:19:1)
    at Object.<anonymous> (...\build\webpack:\node_modules\@serialport\bindings\lib\index.js:6:1)
    at n (...\build\webpack:\webpack\bootstrap:19:1)
    at Object.<anonymous> (...\build\webpack:\node_modules\serialport\lib\index.js:2:1)
    at n (...\build\webpack:\webpack\bootstrap:19:1)
    at Object.<anonymous> (...\build\webpack:\node_modules\osc\src\platforms\osc-node-serialport.js:13:1)
    at n (...\build\webpack:\webpack\bootstrap:19:1)
`

Only the UDP Port is implemented in this build, but by importing the OSC plugin, SerialPort is also built resulting in the TypeError above. The build did work after commenting out 38: `require("./osc-node-serialport.js")` in osc/src/platforms/osc-node.js 

I believe exporting the different platforms and implementations as separate exports would solve this issue, so that UDPPort can be used without requiring osc-node-serialport.js.

**Comment by colinbdclark** [comment]
You don't mention which version of osc.js, nor which version of Node.js.

The SerialPort dependency has been optional since v2.3.1, so there shouldn't be any install-time errors. It looks to me you're using Webpack, and it's trying to process native Node.js modules (it shouldn't be). Have you followed the [instructions for use with Webpack](https://github.com/colinbdclark/osc.js#using-oscjs-with-webpack-etc---help-wanted)?
