### ISSUE TITLE
osc.js -> sonic pi not working. 

### ISSUE THREAD

**Issue by quintendewilde** [colinbdclark/osc.js#169]
Help wanted. 

I can't get osc.js working on rpi3 with sonic pi. 

I used the super collider example and data is pushed. 

```
Sending message /osc/trigger/prophet [
  { type: 'f', value: 0.7236847933121131 },
  { type: 'f', value: 0.05167844031436086 }
] to 192.168.1.23:4560
Sending message /osc/trigger/prophet [
  { type: 'f', value: 0.42208359784187444 },
  { type: 'f', value: 0.08762496307054946 }
] to 192.168.1.23:4560
```

I installed new sonic pi etc.. 
But nothing coming in. Is there a way I can test the osc.js to know if it sends the messages? So I known where the issue is? 

Also why can't I change the `type` or `value` of the `args`??
I throws errors when I change one of these...

**Comment by colinbdclark** [comment]
Hi @quintendewilde, sorry to hear you’re having difficulty. Perhaps it’s an issue of which port you’re using to communicate with Sonic Pi on? The SuperCollider example is set up to work correctly with SuperCollider, but Sonic Pi may be different. I don’t have enough context about your code or what you’re trying to do to be able to help you with this issue.

As for the issue of changing types and values, again, without seeing your code and a better description of the error you’re seeing, I can’t help very much. Have your read the documentation and examples as a starting point? If so, can you send along a simplified example of what you’re having difficulty with?

**Comment by quintendewilde** [comment]
@colinbdclark I'm talking to geniuses at sonic pi forum to know if its a sonic pi issue. 

The code below is the example I got from the super collider example. Because that's the one I understood. (I have lots of knowledge for ESP8266 osc handling wich always worked)
But I don't have a lot of js knowledge compared to it. 

this is the code: 

```
var osc = require("osc");


var udpPort = new osc.UDPPort({
    // This is the port we're listening on.
    localAddress: "127.0.0.1",
    localPort: 4600,

    // This is where sclang is listening for OSC messages.
    remoteAddress: "192.168.1.8",
    remotePort: 4560,
   
});


// Open the socket.
udpPort.open();

// Every second, send an OSC message to SuperCollider
setInterval(function() {
 
    var msg = {
        address: "/osc/trigger/prophet",
        args: [
            {
                type: "f",
                value: Math.random()
            },
            {
                type: "f",
                value: Math.random()
            }
        ]
    };

    console.log("Sending message", msg.address, msg.args, "to", udpPort.options.remoteAddress + ":" + udpPort.options.remotePort);
    udpPort.send(msg);
}, 5000);
```

So ports: I changed ports to local, to specific local and to other machine specific (the example shows my raspberry code that want to talk to my mac running sonic pi with the correct ports)

For the messages themselves I thought I could change the type and or the value. But every time I change those arguments I get an error message. With a string, int or var. 

I just want to send 1 message containing post.length (integer) from a working code that scrapes stuff.  

I've copied the repo and added my files for quick testing will remove them later on today for security.  

https://github.com/quintendewilde/Tools-for-IAC.git

**Comment by colinbdclark** [comment]
Hi @quintendewilde, I think you might be missing what I mean by a "simplified test case or example." If you need help, maybe you can create a little standalone example that shows the error you're receiving when you try to change types or arguments, and paste a clear copy of the error you're receiving. I don't know your code or your repository, and to be totally honest I don't have time on a beautiful sunny Sunday to learn it for you. So simple examples make it much easier for me to share my time with you, rather than having to dive into your entire system.

**Comment by quintendewilde** [comment]
Hi, 

Sorry I've been at this for a week and getting despaired. But you're completely right.  
So I did manage to change the value to an int. 

But when changing the f to a for example. 

I get this: 

```
events.js:292
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property 'writer' of undefined
    at Object.osc.writeArgument (/home/pi/Tools-for-Instagram/node_modules/osc/src/osc.js:761:46)
    at Object.osc.collectArguments (/home/pi/Tools-for-Instagram/node_modules/osc/src/osc.js:791:34)
    at Object.osc.collectMessageParts (/home/pi/Tools-for-Instagram/node_modules/osc/src/osc.js:844:20)
    at Object.osc.writeMessage (/home/pi/Tools-for-Instagram/node_modules/osc/src/osc.js:862:33)
    at Object.osc.writePacket (/home/pi/Tools-for-Instagram/node_modules/osc/src/osc.js:984:24)
    at osc.UDPPort.p.encodeOSC (/home/pi/Tools-for-Instagram/node_modules/osc/src/osc-transports.js:70:27)
    at osc.UDPPort.p.send (/home/pi/Tools-for-Instagram/node_modules/osc/src/osc-transports.js:56:28)
    at Timeout._onTimeout (/home/pi/Tools-for-Instagram/bots/osc.js:37:13)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
Emitted 'error' event on  instance at:
    at osc.UDPPort.p.encodeOSC (/home/pi/Tools-for-Instagram/node_modules/osc/src/osc-transports.js:72:18)
    at osc.UDPPort.p.send (/home/pi/Tools-for-Instagram/node_modules/osc/src/osc-transports.js:56:28)
    [... lines matching original stack trace ...]
    at processTimers (internal/timers.js:492:7)

```

But maybe I should let it go for a day and look back at it tomorrow because I have the feeling I'm missing important things due to my impatience. 

Thanks again though!

**Comment by colinbdclark** [comment]
No worries. A break sometimes helps. This error and description of what you’re trying is much more helpful, thank you.

I don’t actually think there is an “a” type in the OSC specification, so that won’t work. But you did seem to trigger an error deeper in OSC as a result of trying to write an unknown type of value, so I’ll look at fixing it so the error message will be more helpful. When you’re trying “a”, what kind of data do you actually want to send?

**Comment by colinbdclark** [comment]
I'm closing this issue due to inactivity and other issues filed which suggest that you've got things working with Sonic Pi now.
