### ISSUE TITLE
osc.Relay objects should stop forwarding messages when their ports are closed.

### ISSUE THREAD

**Issue by micrem73** [colinbdclark/osc.js#18]
Hi,
using the provided example, i set up a browser client that is able to send and receive OSC to the server. Each time the server receives a OSC message, send another OSC to all clients (this is a patch made in Quartz Composer running on the server, with a OSC listener and a OSC sender, that bridges the one running on the nodejs server).

Everything works fine. The problem happens when a client (mobiles phones) reloads the page.
The server opens another socket (i see the message "A Web Socket connection has been established!").
The old socket remains open on the server.

Whenever the server tries to end an OSC to the mobile that reloaded the page, the server crash, as it's trying to connect to the dead Socket.

How can i handle this, telling the server to check if a socket is till alive before trying to send something to that, or anyway not crashing?

Here is the log error:

events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: not opened
    at WebSocket.send (/Users/michelecremaschiML/Documenti_SSD/Progetti_DigitalPerformance/NerdCabaret/nodeServer/osc.js-examples-master/udp-browser/node_modules/ws/lib/WebSocket.js:213:38)
    at p.sendRaw (/Users/michelecremaschiML/Documenti_SSD/Progetti_DigitalPerformance/NerdCabaret/nodeServer/osc.js-examples-master/udp-browser/node_modules/osc/src/platforms/osc-node.js:257:21)
    at p.send (/Users/michelecremaschiML/Documenti_SSD/Progetti_DigitalPerformance/NerdCabaret/nodeServer/osc.js-examples-master/udp-browser/node_modules/osc/src/osc-transports.js:49:22)
    at listener (/Users/michelecremaschiML/Documenti_SSD/Progetti_DigitalPerformance/NerdCabaret/nodeServer/osc.js-examples-master/udp-browser/node_modules/osc/src/osc-transports.js:108:28)
    at emit (events.js:129:20)
    at p.decodeOSC (/Users/michelecremaschiML/Documenti_SSD/Progetti_DigitalPerformance/NerdCabaret/nodeServer/osc.js-examples-master/udp-browser/node_modules/osc/src/osc-transports.js:62:14)
    at emit (events.js:110:17)
    at Socket.<anonymous> (/Users/michelecremaschiML/Documenti_SSD/Progetti_DigitalPerformance/NerdCabaret/nodeServer/osc.js-examples-master/udp-browser/node_modules/osc/src/platforms/osc-node.js:166:18)
    at Socket.emit (events.js:110:17)
    at UDP.onMessage (dgram.js:472:8)

**Comment by colinbdclark** [comment]
Hi @micrem73,

As far as I know, refreshing the page will cause the browser to close the Web Socket connection, as you're seeing. In turn, the Web Socket server's socket object will emit a <code>close</code> event. osc.js' WebSocketPort automatically listens for these socket close events, and will emit a <code>close</code> event of its own.

So, it sounds like you probably want to listen for the <code>close</code> event on your WebSocketPort instance and, in your application, respond to it by closing down the <code>osc.relay</code> object, which will stop it from relaying data between whatever Port object you're relaying OSC messages from.

Have you tried something like this to close the relay after the WebSocketPort is closed?

    socketPort.on("close", function () {
         relay.close();
    });

Let me know if this works for you, and I can update the examples (or I'm happy to take a pull request if you feel motivated).

Thanks for the question!

**Comment by micrem73** [comment]
Thanks a lot. I impemented the solution.  I'll post a pull request.

**Comment by colinbdclark** [comment]
This issue should be fixed in the <code>osc.Relay</code> implementation, rather than requiring users to do their own housekeeping when relayed ports are closed.
